# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: SourceCodeAnalysis
  jobs:
  - job: sca
    steps:
     - task: dependency-check-build-task@6
       inputs:
         projectName: 'spring-boot-kubernetes'
         scanPath: '$(Build.SourcesDirectory)'
         format: 'HTML'
       displayName: SCA


 