# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: 
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

- stage: SAST 
  jobs:
  - job: sonar
    workspace:
      clean: all
    displayName:  Code Review
    steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonarcloud'
          organization: 'laboratorio-final'
          projectKey: 'Laboratorio-Final_spring-boot-kubernetes'
          projectName: 'spring-boot-kubernetes'

      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'
        displayName: 'Analizar rama actual'

      - task: sonarcloud-buildbreaker@2
        inputs:
          SonarCloud: 'sonarcloud'
          organization: 'laboratorio-final'


- stage: SourceCodeAnalysis
  jobs:
  - job: sca
    steps:
     - task: dependency-check-build-task@6
       inputs:
         projectName: 'spring-boot-kubernetes'
         scanPath: '$(Build.SourcesDirectory)'
         format: 'HTML'
         failOnCVSS: '0'
       displayName: SourceCodeAnalysis

    

 